services:
  - type: web
    plan: free
    name: woowup mail sender
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn email_project.asgi:application"
    preDeploy:
      - "python manage.py test email_app"
