databases:
  - name: woowdb
    plan: free
    databaseName: woowdb
    user: woowdb_user

services:
  - type: web
    plan: free
    name: woowup mail sender
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn email_project.asgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: woowdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4